"""Add users table

Revision ID: 323628e8b53b
Revises: e50abfd32b36
Create Date: 2020-06-19 16:16:00.547056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323628e8b53b'
down_revision = 'e50abfd32b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tweets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_column('tweets', 'user_id')
    # ### end Alembic commands ###
